### PR TITLE
Feature: Collapsible list (for folder structure #6)

### PR DESCRIPTION
**Pull request by steveny9911**
Hi! Not sure if this is still maintained, but I added this collapsible list / folder structure feature for #6 and myself.
Thanks for this extension so far! ❤️

**Description**:
- Display and toggle collapsible list / folder structure
- Display number of articles added in the list

**Implementation**: 
- Modified on the original `EntryList.tsx` component so that list / folder will be displayed first, instead of displaying the all the saved articles
- I added a `FolderItem.tsx` component that display list
- Nested inside is the `EntryItem.tsx` component which is unchanged

**Demo:**
Screen Recording 2020-08-23 at 5 59 18 PM

**Improvements**:
- Not sure why it's slightly laggy, maybe it's just an extension thing
- Maybe it's better to show things similar to how this is organized on the phone app? Click on a list, and then show all the articles
- Display order of the list should be inverted? Seems like on phone app, `Saved` (which is the default list) comes first, and then followed by alphabetical ordering (need to validate this)

### CODE REVIEW

**Review by dqisme — CHANGES_REQUESTED** [review]
Thanks for your PR and feedback. That's amazing.

Could you please also keep enhance on this and remove all the comments in code?

Maybe you can ping me after you think it's complete?

**Comment by steveny9911** [comment]
For sure!
I think I made a mistake and kept pushing on the same branch as I was working on some other features. How about I close this PR and make a new one just for "Collapsible folder" once I did some clean up?

I added the ability to:
- Add and delete an entry
- Add and delete a list


 

Sorry if things look kind of messy, I'm still a bit unfamiliar with React 😥.

**Comment by schradert** [comment]
Is this going to be pulled soon and published on the webstore as a new release? Looks great to me! I got the extension hoping the file structure and entry adding and deleting functionality would be there.

**Comment by steveny9911** [comment]
Seems like I forgot about this after getting a new laptop😓.
I made a new PR for collapsible list only. I'll make new PRs for other changes after that one is closed.

PR https://github.com/dqisme/wikipedia-reading-lists-chrome-extension/pull/13

**Pull request closed without merging**
