### PR TITLE
fix #6 feature: collapsible list

### LINKED ISSUE #6: Can we have the folder structure in this extension?
First thank you for this great extension!. I am using list name to group items on Android application, but I found this extension do not show the folder structure.

### PR DESCRIPTION
**Pull request by steveny9911**
From PR https://github.com/dqisme/wikipedia-reading-lists-chrome-extension/pull/11

open-list

### CODE REVIEW

**Comment by dqisme** [comment]
Hey @steveny9911 thanks very much for this PR and it is an enhanced implementation.
Could you please also try to fix the width shaking?

**Comment by steveny9911** [comment]
> Hey @steveny9911 thanks very much for this PR and it is an enhanced implementation.
> Could you please also try to fix the width shaking?

Ya it's interesting; don't know why it's only showing here (unlike the previous GIF). I'll look into it.

**Comment by steveny9911** [comment]
@dqisme Seems like I could just set a fixed `width: 320` to `EntryList` (instead of `minWidth: 320`)
```tsx
// EntryList.tsx : 19

    list: {
      width: 320, // <--- replaced minWidth with width
      maxHeight: 480,
      overflowY: 'auto',
    },
```

**Comment by dqisme** [comment]
Sorry to reply so late. Do you think we can make it as a fixed height for each expansion? And even we can make it able to open one and only one folder? Does this make sense for you please?

**Comment by steveny9911** [comment]
No worries!
- I think it might be a bit hard to make a fix height for each expansion. The overall popup has a max height but I'm not sure if it's easy to set a fix height for each expansion - so that there is a scroll inside (?) not sure if I understood this correctly.
- I think I can take a look if I can make it open one folder at a time

**Pull request closed without merging**
